# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11yto0lt1D9IibL1OTHNIt7mGCyui_jCp
"""

import random
import time

# Accept min and max temperature
min_temp = float(input("Enter minimum temperature limit: "))
max_temp = float(input("Enter maximum temperature limit: "))

print("\nTemperature Monitoring Started...\n")

# Generate temperature every 2 seconds (10 readings example)
for i in range(10):
    temp = random.uniform(0, 100)   # random temperature between 0 and 100
    print(f"Current Temperature: {temp:.2f}")

    # Compare with limits
    if temp > max_temp:
        print("ALERT: Temperature is too HIGH")
    elif temp < min_temp:
        print("ALERT: Temperature is too LOW")
    else:
        print("Temperature is NORMAL")

    print("---------------------")
    time.sleep(2)   # wait 2 seconds